### ISSUE TITLE
problem with tar.xz.ac lineage os source code file 

### ISSUE THREAD

**Issue by ali1997** [regalstreak/skadoosh#144]
the archive cannot be extracted and this the error on ark and other archive tools  

Ark was not able to open LineageOS-cm-14.1-full-20170713.tar.ac. No suitable plugin found.

Ark does not seem to support this file type

**Comment by regalstreak** [comment]
https://forum.xda-developers.com/showpost.php?s=988623e31fd09b7061c1717573e886be&p=63435197&postcount=4

Here instructions were given to extract it.

**Comment by ali1997** [comment]
Bro this is very massive and large..  Can be more comppressed and only 2parts or 1 part?!!

**Comment by regalstreak** [comment]
No. This is the maximum compression we have achieved
