### ISSUE TITLE
how to update the downloaded source

### ISSUE THREAD

**Issue by aymende7** [regalstreak/skadoosh#145]

**Comment by regalstreak** [comment]
Read the FAQ on thread. What didn't you understand?

**Comment by aymende7** [comment]
how to keep the downloaded code fresh and up to date

**Comment by regalstreak** [comment]
```repo sync -c -f --force-sync --no-clone-bundle --no-tags -j8```

**Comment by regalstreak** [comment]
Just run the command again. It will fetch and update

**Comment by aymende7** [comment]
thanks a lot

**Comment by aymende7** [comment]
https://hastebin.com/acamigavar.scala
error: Exited sync due to fetch errors
