### ISSUE TITLE
split archives.

### ISSUE THREAD

**Issue by thewisenerd** [regalstreak/skadoosh#48]
why not split the tar archives for easier download tracking?

**Comment by msfjarvis** [comment]
Because that adds another point for morons to mess up and us to have more
headaches?

**Comment by thewisenerd** [comment]
_very_ big download files defeat the point of this project, even if the downloads are resumable.

I have a shitty ISP who redirects every request post FUP to a html page. have had many corrupted downloads because of that. and this is just one example of why big files are a bad idea.

**Comment by regalstreak** [comment]
Well 3GiB in front of 20GiB isn't big. We can do so much. It's simple shell. We can even put that stuff in a hard disk and deliver it to your house, but we need what just works. You can try using the good old proprietary Internet Download Manager for solving this issue. It can change links after the downloads corrupt or something too.

**Comment by regalstreak** [comment]
If you feel the need for it, just submit up a pull request with configurable options. We will be happy to review and merge. 
We can bring in minimal manifests here tho. Like not syncing the extra useless projects maybe.

**Comment by msfjarvis** [comment]
``` shell
harsh@harsh-Inspiron-3558:~$ split --additional-suffix=skadoosh --suffix-length=1 --numeric-suffixes=1 --verbose --bytes=200M test.tar.gz
creating file 'x1skadoosh'
creating file 'x2skadoosh'
creating file 'x3skadoosh'
creating file 'x4skadoosh'
creating file 'x5skadoosh'
```

Well this didn't work well enough.

**Comment by msfjarvis** [comment]
Anyone has any brighter ideas?

**Comment by regalstreak** [comment]
@MSF-Jarvis Well this is alright but I don't want moar confusions

**Comment by thewisenerd** [comment]
pipe tar output to split? 

also, _surprise, surprise!_ turn off verbose (-v) option on tar please. trust me. you do not want to output that to the terminal. although, oh! how better to keep track progress then? :confused:

**Comment by msfjarvis** [comment]
@thewisenerd Filenames are shit from split, we need a consistent and dependable naming scheme. Fix it if you can, I can pipe tar output to split when that's sorted.

**Comment by thewisenerd** [comment]
@MSF-Jarvis then you're obviously using split wrong :neutral_face: 

why i suggested piping tar output to split is to directly split the file instead of having to first make it into one big tar file, and then further splitting it.

dunno why you're complicating stuff, but I just did:

```
thewisenerdv2@eniac-v2:~/works/splittest$ dd if=/dev/zero of=test.img bs=104857600 count=1
1+0 records in
1+0 records out
104857600 bytes (105 MB, 100 MiB) copied, 0.328272 s, 319 MB/s
thewisenerdv2@eniac-v2:~/works/splittest$ ls
test.img
thewisenerdv2@eniac-v2:~/works/splittest$ ls
test.img
thewisenerdv2@eniac-v2:~/works/splittest$ du -h
101M    .
thewisenerdv2@eniac-v2:~/works/splittest$ du -h *
100M    test.img
thewisenerdv2@eniac-v2:~/works/splittest$ cat test.img 
^C
thewisenerdv2@eniac-v2:~/works/splittest$ ls
test.img
thewisenerdv2@eniac-v2:~/works/splittest$ ls
test.img
thewisenerdv2@eniac-v2:~/works/splittest$ ls -la
total 102408
drwxrwxr-x  2 thewisenerdv2 thewisenerdv2      4096 Sep 22 16:39 .
drwxr-xr-x 10 thewisenerdv2 thewisenerdv2      4096 Sep 22 16:37 ..
-rw-rw-r--  1 thewisenerdv2 thewisenerdv2 104857600 Sep 22 16:39 test.img
thewisenerdv2@eniac-v2:~/works/splittest$ split --bytes=1M test.img repo.img.skadoosh.
thewisenerdv2@eniac-v2:~/works/splittest$ ls
repo.img.skadoosh.aa  repo.img.skadoosh.ap  repo.img.skadoosh.be  repo.img.skadoosh.bt  repo.img.skadoosh.ci  repo.img.skadoosh.cx  repo.img.skadoosh.dm
repo.img.skadoosh.ab  repo.img.skadoosh.aq  repo.img.skadoosh.bf  repo.img.skadoosh.bu  repo.img.skadoosh.cj  repo.img.skadoosh.cy  repo.img.skadoosh.dn
repo.img.skadoosh.ac  repo.img.skadoosh.ar  repo.img.skadoosh.bg  repo.img.skadoosh.bv  repo.img.skadoosh.ck  repo.img.skadoosh.cz  repo.img.skadoosh.do
repo.img.skadoosh.ad  repo.img.skadoosh.as  repo.img.skadoosh.bh  repo.img.skadoosh.bw  repo.img.skadoosh.cl  repo.img.skadoosh.da  repo.img.skadoosh.dp
repo.img.skadoosh.ae  repo.img.skadoosh.at  repo.img.skadoosh.bi  repo.img.skadoosh.bx  repo.img.skadoosh.cm  repo.img.skadoosh.db  repo.img.skadoosh.dq
repo.img.skadoosh.af  repo.img.skadoosh.au  repo.img.skadoosh.bj  repo.img.skadoosh.by  repo.img.skadoosh.cn  repo.img.skadoosh.dc  repo.img.skadoosh.dr
repo.img.skadoosh.ag  repo.img.skadoosh.av  repo.img.skadoosh.bk  repo.img.skadoosh.bz  repo.img.skadoosh.co  repo.img.skadoosh.dd  repo.img.skadoosh.ds
repo.img.skadoosh.ah  repo.img.skadoosh.aw  repo.img.skadoosh.bl  repo.img.skadoosh.ca  repo.img.skadoosh.cp  repo.img.skadoosh.de  repo.img.skadoosh.dt
repo.img.skadoosh.ai  repo.img.skadoosh.ax  repo.img.skadoosh.bm  repo.img.skadoosh.cb  repo.img.skadoosh.cq  repo.img.skadoosh.df  repo.img.skadoosh.du
repo.img.skadoosh.aj  repo.img.skadoosh.ay  repo.img.skadoosh.bn  repo.img.skadoosh.cc  repo.img.skadoosh.cr  repo.img.skadoosh.dg  repo.img.skadoosh.dv
repo.img.skadoosh.ak  repo.img.skadoosh.az  repo.img.skadoosh.bo  repo.img.skadoosh.cd  repo.img.skadoosh.cs  repo.img.skadoosh.dh  test.img
repo.img.skadoosh.al  repo.img.skadoosh.ba  repo.img.skadoosh.bp  repo.img.skadoosh.ce  repo.img.skadoosh.ct  repo.img.skadoosh.di
repo.img.skadoosh.am  repo.img.skadoosh.bb  repo.img.skadoosh.bq  repo.img.skadoosh.cf  repo.img.skadoosh.cu  repo.img.skadoosh.dj
repo.img.skadoosh.an  repo.img.skadoosh.bc  repo.img.skadoosh.br  repo.img.skadoosh.cg  repo.img.skadoosh.cv  repo.img.skadoosh.dk
repo.img.skadoosh.ao  repo.img.skadoosh.bd  repo.img.skadoosh.bs  repo.img.skadoosh.ch  repo.img.skadoosh.cw  repo.img.skadoosh.dl
thewisenerdv2@eniac-v2:~/works/splittest$ 
thewisenerdv2@eniac-v2:~/works/splittest$ 
```

**Comment by msfjarvis** [comment]
@thewisenerd Fine, looking good enough for me, but @regalstreak must approve before I close this with a commit

**Comment by regalstreak** [comment]
@MSF-Jarvis Tha fuck how do you expect a guy to download 17482638 files

**Comment by msfjarvis** [comment]
@regalstreak By using a bigger block size?

**Comment by regalstreak** [comment]
@MSF-Jarvis Don't know but this seems to confuse me. Maybe add some shit as a toggle.

**Comment by msfjarvis** [comment]
@regalstreak No toggle, but yes we will need extraction scripts

**Comment by regalstreak** [comment]
@MSF-Jarvis Add a toggle like we have for repo/norepo/shit

**Comment by msfjarvis** [comment]
@regalstreak Yeah that'll work

**Comment by sagarshah1729** [comment]
@MSF-Jarvis This is not related to your though..

**Comment by MSF-Jarvis** [comment]
Erm what? I'm missing something there

**Comment by regalstreak** [comment]
What happened to that comment by sagar shah?

**Comment by msfjarvis** [comment]
~~I deleted it.....i guess~~ He messed up I guess

**Comment by regalstreak** [comment]
@MSF-Jarvis what

**Comment by msfjarvis** [comment]
read dat edit

**Comment by regalstreak** [comment]
@MSF-Jarvis am using telegram to post comments. I rock.

**Comment by msfjarvis** [comment]
Am using Dad's laptop in teh middle of the night. I rock even more. BTW I gave you that bot, so go sux dix

**Comment by regalstreak** [comment]
@MSF-Jarvis is very old. using since pre marshmallow days. I don't sux dix.

**Comment by msfjarvis** [comment]
mah life sux dix

**Comment by regalstreak** [comment]
Thats good for you bruhh

**Comment by ShadowReaper1** [comment]
Why not use split utility for breaking repo.tar.xz into several parts then cat to join those parts?
Example-

split -b 3072M repo.tar.xz "repo.tar.xz.aa"

This will will create several 3GB parts of repo then to join them use

cat repo.tar.xz.\* > repo.tar.xz

**Comment by thewisenerd** [comment]
um, lemme see:

read files to create .tar.xz > read .tar'ed file > split file

why not just pipe tar output to split? is multiple pipe re-direction a thing?

**Comment by ShadowReaper1** [comment]
Ok so here it goes -
"tar -I pxz -cvf .repo/ | split -b 4096M - repo.tar.xz." then "cat repo.tar.xz.* > repo.tar.xz && tar --extract -f repo.tar.xz && rm -rf repo.tar.*"
This will create almost 5 4GB archives but we can't join those files and extract them at the same time so we have to use "&&" to continue the process and delete archives but I have only tested with standard gzip idk if it'll work with lzma compression but it should work however it's easier to provide a extraction script within the zip to make this process easier.

**Comment by ShadowReaper1** [comment]
seems like it's not working as expected with lzma compression now.

**Comment by thewisenerd** [comment]
tar can output to stdout (piping it to split, hey!). one up that, and ```tee``` it to split also. when extracting, tar can read from stdin; so, pipe ```cat repo.tar.xz.*``` to tar with flags to read from stdin.

###### // disclaimer: all woolly talk above. may or may not be true.

**Comment by regalstreak** [comment]
Well @thewisenerd this is done now check lol
