### ISSUE TITLE
Will it download the entire sources or just the latest snapshots

### ISSUE THREAD

**Issue by shivamdev-lgtm** [regalstreak/skadoosh#97]
Well I have not used it yet but I want to ask (because I don't have unlimited bandwidth) that will it download even the repo file or just the snapshots..
And also I want to ask that is it a compulsion to upload the compressed version or not

**Comment by regalstreak** [comment]
It will download the .repo folder in shallow or full.
In shallow, it will only fetch the latest commits or the "HEAD" so the file size will be a lot lower than full
You will also be able to update it via ```repo sync```
But if you do not want to use data, you can use ```repo sync --local-only``` so it doesn't fetch from network and only syncs the local work tree. 

If you have further doubts, just ask me. And skadoosh is live again!
